import { PrismaClient } from "@prisma/client";
import { Decimal } from "@prisma/client/runtime/library";

const prisma = new PrismaClient();

async function main() {
  await prisma.coupon.createMany({
    data: [
      {
        id: "f581491c-5af8-4f86-b22f-c82141d092e1",
        code: "NATURA20",
        expireAt: new Date("2026-08-05"),
        percentage: 20,
      },
      {
        id: "854aa39f-1060-4c93-831e-4f4297ddb1d9",
        code: "NATURA15",
        expireAt: new Date("2026-08-05"),
        percentage: 15,
      }
    ],
    skipDuplicates: true,
  });
  await prisma.product.createMany({
    skipDuplicates: true,
    data: [
      {
        id: "897e0e11-bff5-45d5-89ed-2f9df3a023fb",
        name: "Natura Luna Perfume",
        image: "natura-luna.jpg",
        slug: "natura-luna-perfume",
        rating: 4.2,
        price: new Decimal(91.37),
        stock: 10,
        category: "PERFUME",
      },
      {
        id: "f3a7fd16-a79c-4c5a-9b12-579032568ef6",
        name: "Kaiak Masculino Natura 100 Ml",
        image: "kaiak-masculino.jpg",
        slug: "kaiak-masculino-natura-100ml",
        rating: 4.9,
        price: new Decimal(119.90),
        stock: 10,
        category: "PERFUME",
      },
      {
        id: "2dd674de-3ea1-4bbc-a0f7-d0886d16bb3c",
        name: "Essencial Ato Deo Parfum Feminino - 100 Ml",
        image: "essencial-ato-deo.jpg",
        slug: "essencial-ato-deo",
        rating: 4.8,
        price: new Decimal(259.90),
        stock: 10,
        category: "PERFUME",
      },
      {
        id: "debf949c-4482-4b17-8972-11ca81efbef0",
        name: "Natura Una Deo Parfum Feminino - 75 ml",
        image: "natura-una-deo-parfum-feminino.jpeg",
        slug: "natura-una-deo-parfum-feminino",
        rating: 3.5,
        price: new Decimal(400.90),
        discountPercentege: 30,
        stock: 10,
        category: "PERFUME",
      },
      {
        id: "add9962d-d084-48fe-a115-c5cd2961485c",
        name: "Essencial Exclusivo Feminino 100 Ml",
        image: "essencial-exclusivo-feminino.jpg",
        slug: "essencial-exclusivo-feminino",
        rating: 4.9,
        price: new Decimal(154.90),
        stock: 10,
        category: "PERFUME",
      },
      {
        id: "04cdb98e-48d7-4f82-b21c-07c871a96ac1",
        name: "Ilía Deo Parfum 50 Ml",
        image: "ilia-deo-parfum.jpg",
        slug: "ilia-deo-parfum",
        rating: 4.9,
        price: new Decimal(173.90),
        stock: 10,
        category: "PERFUME",
      },
      {
        id: "b70c439f-0d8b-4b54-ac41-c117407a98bf",
        name: "Desodorante Perfume Natura Homem Essence 100 ml",
        image: "desodorante-perfume-natura.jpg",
        slug: "desodorante-perfume-natura",
        rating: 5,
        price: new Decimal(204.90),
        discountPercentege: 15,
        stock: 10,
        category: "PERFUME",
      },
      {
        id: "1b736ab3-3a09-42c9-ab58-2e1cdf52f9b1",
        name: "Homem Tato Deo Parfum 100 Ml",
        image: "homem-tato-deo-parfum.jpg",
        slug: "homem-tato-deo-parfum",
        rating: 4.9,
        price: new Decimal(204.90),
        stock: 10,
        category: "PERFUME",
      },
      {
        id: "92d4f2c3-208e-4a66-9805-3ac864c77f29",
        name: "Una Senses Deo Parfum Feminino Natura - 75 Ml",
        image: "una-senses-deo-parfum.jpg",
        slug: "una-senses-deo-parfum",
        rating: 5,
        price: new Decimal(360.90),
        discountPercentege: 7,
        stock: 10,
        category: "PERFUME",
      },
      {
        id: "5c214d72-0781-4cb7-883c-a7d0533b519a",
        name: "Luna Colônia 75ml",
        image: "luna-colonia.jpg",
        slug: "luna-colonia",
        rating: 4.9,
        price: new Decimal(169.90),
        stock: 10,
        category: "PERFUME",
      },
      {
        id: "dcda71b4-ac54-4242-a99d-ee5a33875713",
        name: "Sabonete Algodão Tododia",
        image: "sabonete-algodao-tododia.jpg",
        slug: "sabonete-algodao-tododia",
        rating: 5,
        price: new Decimal(31.40),
        stock: 10,
        category: "COSMETIC",
      },
      {
        id: "25305eef-d4e0-4572-a8e6-201700dab08a",
        name: "Sabonete Barra Tododia Alecrim e Sálvia",
        image: "sabonete-barra-tododia-alecrim-e-salvia.jpg",
        slug: "sabonete-barra-tododia-alecrim-e-salvia",
        rating: 5,
        price: new Decimal(31.40),
        stock: 10,
        category: "COSMETIC",
      },
      {
        id: "5d9030c2-b6aa-4582-9261-d7b345984f05",
        name: "Tododia Sabonete Barra Ameixa e Flor De Baunilha",
        image: "tododia-sabonete-barra-ameixa-e-flor-de-baunilha.jpg",
        slug: "tododia-sabonete-barra-ameixa-e-flor-de-baunilha",
        rating: 5,
        price: new Decimal(31.40),
        stock: 10,
        category: "COSMETIC",
      },
      {
        id: "42665d9e-9143-48ff-89da-770dffa097b4",
        name: "Sabonete Em Barra Tododia Todanoite Chá De Camomila e Lavanda",
        image: "sabonete-em-barra-tododia-todanoite-cha-de-camomila-e-lavanda.jpg",
        slug: "sabonete-em-barra-tododia-todanoite-cha-de-camomila-e-lavanda",
        rating: 5,
        price: new Decimal(28.20),
        stock: 10,
        category: "COSMETIC",
      },
      {
        id: "af87bf0c-4b27-4f3d-a781-ee6e24e2af48",
        name: "Natura Ekos Sabonete Em Barra Cremoso e Esfoliante",
        image: "natura-ekos-sabonete-em-barra-cremoso-e-esfoliante.jpg",
        slug: "natura-ekos-sabonete-em-barra-cremoso-e-esfoliante",
        rating: 5,
        price: new Decimal(37.50),
        stock: 10,
        category: "COSMETIC",
        discountPercentege: 5,
      },
      {
        id: "6dfd9e6c-ed08-4f6d-aff5-4a4685a5c53c",
        name: "Sabonete Barra Tododia Macadâmia Natura",
        image: "sabonete-barra-tododia-macadamia-natura.jpg",
        slug: "sabonete-barra-tododia-macadamia-natura",
        rating: 5,
        price: new Decimal(31.40),
        stock: 10,
        category: "COSMETIC",
      },
      {
        id: "5ffca8ea-9f6b-4435-8e97-50b12870c3ee",
        name: "Sabonete Em Barra Natura Ekos Cremoso e Esfoliante Maracujá",
        image: "sabonete-em-barra-natura-ekos-cremoso-e-esfoliante-maracuja.jpg",
        slug: "ssabonete-em-barra-natura-ekos-cremoso-e-esfoliante-maracuja",
        rating: 5,
        price: new Decimal(31.40),
        stock: 10,
        category: "COSMETIC",
      },
      {
        id: "3849cca8-e55f-40a0-82e8-8c14a88fde6e",
        name: "Sabonete em Barra Tododia Todanoite 5 un de 90 g",
        image: "sabonete-em-barra-tododia-todanoite-5un-de-90g.jpg",
        slug: "sabonete-em-barra-tododia-todanoite-5un-de-90g",
        rating: 1,
        price: new Decimal(31.40),
        stock: 10,
        category: "COSMETIC",
      },
      {
        id: "71f87e1c-d8ca-4043-bdd6-a692bc5a35d6",
        name: "Sabonete Barra Tododia Alecrim e Sálvia Natura",
        image: "sabonete-barra-tododia-alecrim-e-salvia-natura.jpg",
        slug: "sabonete-barra-tododia-alecrim-e-salvia-natura",
        rating: 5,
        price: new Decimal(31.40),
        stock: 10,
        category: "COSMETIC",
      },
      {
        id: "bb3cd428-29eb-43f4-a70f-c9ce1eb3ed3b",
        name: "Sabonete Líquido Em Gel Tododia Alecrim e Sálvia 390g",
        image: "sabonete-liquido-em-gel-tododia-alecrim-e-salvia-390g.jpg",
        slug: "sabonete-liquido-em-gel-tododia-alecrim-e-salvia-390g",
        rating: 5,
        price: new Decimal(31.40),
        stock: 10,
        category: "COSMETIC",
      },
    ]
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });